<?php

namespace UESNA\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AncienRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AncienRepository extends EntityRepository
{
}
