<?php

namespace UESNA\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * WilayaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WilayaRepository extends EntityRepository
{
}
